import { useState, type ClipboardEvent } from "react";
import type { CalculationResult, ProfileInput } from "./types";

const elevation: ProfileInput = { mode:"xyr", points:[[0,0,0],[5.191,-1.294,10],[27.647,-1.294,10],[32.273,-.141,10],[42.729,-.141,10],[47.355,-1.294,10],[69.811,-1.294,10],[75,0,0]].map(([x,y,value])=>({x,y,value})) };
const plan: ProfileInput = { mode:"xyr", points:[[0,0,0],[25,3.4613,100],[75,0,0]].map(([x,y,value])=>({x,y,value})) };
const fmt=(n:number,d=3)=>Number.isFinite(n)?n.toFixed(d):"—";

function Editor({title,value,onChange}:{title:string;value:ProfileInput;onChange:(x:ProfileInput)=>void}) {
 const set=(i:number,k:"x"|"y"|"value",v:string)=>onChange({...value,points:value.points.map((p,j)=>j===i?{...p,[k]:Number(v)}:p)});
 const paste=(event:ClipboardEvent)=>{const rows=event.clipboardData.getData("text").trim().split(/\r?\n/).map(row=>row.split(/\t|,/).slice(0,3).map(Number)).filter(row=>row.length===3&&row.every(Number.isFinite));if(!rows.length)return;event.preventDefault();onChange({...value,points:rows.map(([x,y,val])=>({x,y,value:val}))})};
 const xs=value.points.map(p=>p.x),ys=value.points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),px=(x:number)=>8+(x-minX)/(maxX-minX||1)*164,py=(y:number)=>48-(y-minY)/(maxY-minY||1)*40;
 return <section className="panel"><div className="head"><div><h2>{title}</h2><small>{value.mode==="xyr"?"角点 + 倒角半径":"CAD 节点 + bulge；b 属于当前点到下一点"}</small></div><select value={value.mode} onChange={e=>onChange({...value,mode:e.target.value as "xyr"|"xyb"})}><option value="xyr">x / y / r</option><option value="xyb">x / y / b</option></select></div><div className="profile-preview"><span>线形预览</span><svg viewBox="0 0 180 58"><polyline points={value.points.map(p=>`${px(p.x)},${py(p.y)}`).join(" ")}/>{value.points.map((p,i)=><circle key={i} cx={px(p.x)} cy={py(p.y)} r="2.5"/>)}</svg></div><table onPaste={paste}><thead><tr><th>#</th><th>x (m)</th><th>y (m)</th><th>{value.mode==="xyr"?"r (m)":"b"}</th><th/></tr></thead><tbody>{value.points.map((p,i)=><tr key={i}><td>{i+1}</td>{(["x","y","value"] as const).map(k=><td key={k}><input type="number" step="any" value={p[k]} onChange={e=>set(i,k,e.target.value)}/></td>)}<td><button className="delete" aria-label="删除该节点" onClick={()=>value.points.length>2&&onChange({...value,points:value.points.filter((_,j)=>j!==i)})}>×</button></td></tr>)}</tbody></table><small>可从 Excel 复制三列 x、y、{value.mode==="xyr"?"r":"b"} 后直接粘贴到表格。</small><button onClick={()=>onChange({...value,points:[...value.points,{...value.points.at(-1)!,x:value.points.at(-1)!.x+5,value:0}]})}>+ 添加节点</button></section>
}

function Chart({result}:{result:CalculationResult}) {
 const d=result.distribution,w=920,h=150,l=75,r=25,x0=d[0].x,x1=d.at(-1)!.x,sx=(x:number)=>l+(x-x0)/(x1-x0)*(w-l-r);
 const rows:[keyof typeof d[number],string,string][]=[["plan_y","平面线形","m"],["elevation_y","立面线形","m"],["stress","应力分布","MPa"],["elongation_mm","相对不动点累计伸长量","mm"]];
 return <section className="panel chart"><h2>钢束综合分布</h2><svg viewBox={`0 0 ${w} ${h*4+40}`}><text x={w/2} y={h*4+30} textAnchor="middle">共同里程 x（m）</text>{rows.map(([key,title,unit],i)=>{const vals=d.map(p=>p[key] as number),mn=Math.min(...vals),mx=Math.max(...vals),pad=Math.max((mx-mn)*.12,.001),lo=mn-pad,hi=mx+pad,top=i*h+22,sy=(v:number)=>top+h-40-(v-lo)/(hi-lo)*(h-65),path=d.map((p,j)=>`${j?"L":"M"}${sx(p.x)},${sy(p[key] as number)}`).join(" ");return <g key={title}><text x={l} y={top-7}>{title}（{unit}）</text><line x1={l} x2={w-r} y1={sy(0)} y2={sy(0)} className="zero"/><line x1={l} x2={w-r} y1={top+h-40} y2={top+h-40} className="axis"/><path d={path} className={`line line${i}`}/>{result.balance_x!==null&&<><line x1={sx(result.balance_x)} x2={sx(result.balance_x)} y1={top} y2={top+h-40} className="balance"/>{i===0&&<text x={sx(result.balance_x)+4} y={top+12} className="red">不动点 {fmt(result.balance_x,2)}m</text>}</>}</g>})}</svg></section>
}

export default function App(){const[e,setE]=useState(elevation),[p,setP]=useState(plan),[q,setQ]=useState({k:.0015,mu:.25,elastic_modulus:195000,left_stress:1395,right_stress:1395}),[res,setRes]=useState<CalculationResult|null>(null),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const calc=async()=>{setBusy(true);setErr("");try{const r=await fetch("http://localhost:8000/api/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({elevation:e,plan:p,...q})}),b=await r.json();if(!r.ok)throw Error(b.detail||"计算失败");setRes(b)}catch(x){setErr(x instanceof Error?x.message:"计算失败")}finally{setBusy(false)}};return <main><header><b>TENDON MVP</b><h1>预应力钢束理论伸长量计算</h1><p>输入立面与平面线形，复核应力、不动点和理论伸长量。</p></header><div className="grid"><Editor title="立面线形" value={e} onChange={setE}/><Editor title="平面线形" value={p} onChange={setP}/></div><section className="panel"><div className="head"><div><h2>计算参数</h2><small>默认值仅用于快速计算，应按设计文件或者相关规范取值。</small></div><button className="primary" onClick={calc} disabled={busy}>{busy?"计算中…":"开始计算"}</button></div><div className="params">{([['k','孔道偏差系数 k'],['mu','摩阻系数 μ'],['elastic_modulus','钢束弹性模量 Ep（MPa）'],['left_stress','左端张拉应力（MPa）'],['right_stress','右端张拉应力（MPa）']] as const).map(([k,label])=><label key={k}>{label}<input type="number" step="any" value={q[k]} onChange={e=>setQ({...q,[k]:Number(e.target.value)})}/></label>)}</div></section>{err&&<p className="error">{err}</p>}{res&&<><div className="metrics">{[['钢束总长',`${fmt(res.total_length)} m`],['不动点',res.balance_x===null?'—':`${fmt(res.balance_x)} m`],['左端伸长量',`${fmt(res.left_elongation_mm,2)} mm`],['右端伸长量',`${fmt(res.right_elongation_mm,2)} mm`],['总伸长量',`${fmt(res.total_elongation_mm,2)} mm`],['累计转角',`${fmt(res.total_turn,4)} rad`]].map(([a,b])=><div className="metric" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><Chart result={res}/><section className="panel"><h2>分段计算明细</h2><table><thead><tr><th>来源</th><th>x 起</th><th>x 终</th><th>长度</th><th>转角</th><th>平均应力</th><th>伸长量</th></tr></thead><tbody>{res.segments.map((s,i)=><tr key={i}><td>{s.source==='left'?'左端':'右端'}</td><td>{fmt(s.x_start)}</td><td>{fmt(s.x_end)}</td><td>{fmt(s.length)}</td><td>{fmt(s.turn,5)}</td><td>{fmt(s.average_stress,1)}</td><td>{fmt(s.elongation_mm,2)}</td></tr>)}</tbody></table></section></>}</main>}
