import { useState, type MouseEvent } from "react";
import type { CalculationResult } from "./types";

const fmt=(n:number,d=2)=>n.toFixed(d);

export default function Chart({result}:{result:CalculationResult}){
 const [tip,setTip]=useState<number|null>(null),d=result.distribution,w=920,h=150,l=88,r=25,x0=d[0].x,x1=d.at(-1)!.x,plot=w-l-r;
 const sx=(x:number)=>l+(x-x0)/(x1-x0)*plot;
 const rows:[keyof typeof d[number],string,string][]=[["plan_y","平面 y","m"],["elevation_y","立面 y","m"],["stress","应力","MPa"],["elongation_mm","伸长量","mm"]];
 const hover=(e:MouseEvent<SVGRectElement>)=>{const b=e.currentTarget.ownerSVGElement!.getBoundingClientRect(),u=Math.max(0,Math.min(1,(e.clientX-b.left-b.width*l/w)/(b.width*plot/w))),x=x0+u*(x1-x0);setTip(d.reduce((best,p,i)=>Math.abs(p.x-x)<Math.abs(d[best].x-x)?i:best,0))};
 return <section className="panel chart"><h2>钢束综合分布</h2><div className="chart-wrap"><svg viewBox={`0 0 ${w} ${h*4+46}`} onMouseLeave={()=>setTip(null)}>{rows.map(([key,title,unit],i)=>{const raw=d.map(p=>key==="elongation_mm"?Math.max(0,p[key] as number):p[key] as number),mn=i===3?0:Math.min(...raw),mx=Math.max(...raw),pad=Math.max((mx-mn)*.12,.001),lo=mn,hi=mx+pad,top=i*h+20,sy=(v:number)=>top+h-34-(v-lo)/(hi-lo)*(h-58),path=d.map((p,j)=>`${j?"L":"M"}${sx(p.x)},${sy(key==="elongation_mm"?Math.max(0,p[key] as number):p[key] as number)}`).join(" ");return <g key={title}><rect x={l} y={top} width={plot} height={h-34} className="frame"/>{[.25,.5,.75].map(v=><line key={`h${v}`} x1={l} x2={w-r} y1={top+(h-34)*v} y2={top+(h-34)*v} className="gridline"/>)}{[.2,.4,.6,.8].map(v=><line key={`v${v}`} x1={l+plot*v} x2={l+plot*v} y1={top} y2={top+h-34} className="gridline"/>)}<text x="18" y={top+(h-34)/2-5} className="y-title">{title}</text><text x="18" y={top+(h-34)/2+10} className="y-title unit">({unit})</text><text x={l-8} y={top+11} textAnchor="end" className="tick">{fmt(hi,key==="stress"?0:2)}</text><text x={l-8} y={top+h-36} textAnchor="end" className="tick">{fmt(lo,key==="stress"?0:2)}</text><path d={path} className={`line line${i}`}/>{i<2&&d.filter((_,j)=>j===0||j===d.length-1||j%Math.max(1,Math.floor(d.length/5))===0).map((p,j)=><circle key={j} cx={sx(p.x)} cy={sy(p[key] as number)} r="2.5" className="keypoint"/>)}{result.balance_x!==null&&<><line x1={sx(result.balance_x)} x2={sx(result.balance_x)} y1={top} y2={top+h-34} className="balance"/>{i===0&&<text x={sx(result.balance_x)+4} y={top+13} className="red">不动点</text>}</>}<rect x={l} y={top} width={plot} height={h-34} className="hover-zone" onMouseMove={hover}/></g>})}{[0,.2,.4,.6,.8,1].map(v=><text key={v} x={l+plot*v} y={h*4+24} textAnchor={v===0?"start":v===1?"end":"middle"} className="tick">{fmt(x0+(x1-x0)*v)}</text>)}<text x={w/2} y={h*4+40} textAnchor="middle">x (m)</text></svg>{tip!==null&&<div className="tooltip">x = {fmt(d[tip].x)} m<br/>平面 y = {fmt(d[tip].plan_y)} m<br/>立面 y = {fmt(d[tip].elevation_y)} m<br/>应力 = {fmt(d[tip].stress,1)} MPa<br/>伸长量 = {fmt(Math.max(0,d[tip].elongation_mm))} mm</div>}</div></section>
}
